### PR TITLE
fix(prov-dev): Fix issue where sas token url was url encoded before being signed

### PR DESCRIPTION
**Pull request by timtay-microsoft**
the old flow was url encode -> sign -> url encode again

the correct flow is simply sign -> url encode

fixes issue #989

### CODE REVIEW

**Review by abhipsaMisra — APPROVED** [review]
Given that we had a unit test that expected the string to be signed to already be url encoded, any idea why we might have designed it that way?

**Comment by timtay-microsoft** [comment]
> Given that we had a unit test that expected the string to be signed to already be url encoded, any idea why we might have designed it that way?

Not a clue. It was definitely being url encoded twice, which seems accidental to me

**Pull request merged**
