### PR TITLE
release(2020-11-16): bump package versions

### PR DESCRIPTION
**Pull request by timtay-microsoft**
## Java IotHub Device Client (com.microsoft.azure.sdk.iot:iot-device-client:1.27.0)

- Added support for configuring amqp layer timeout values ([#908](https://github.com/Azure/azure-iot-sdk-java/pull/908))

### Bug fixes
- Fixed bug where provisioning device client URL encoded SAS token URL before signing and after signing ([#990](https://github.com/Azure/azure-iot-sdk-java/pull/990))

https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.27.0/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot.provisioning/provisioning-device-client/1.8.5/jar

old
{
    "device": "1.26.0",
    "service": "1.26.0",
    "deps": "0.11.0",
    "securityProvider": "1.3.0",
    "tpmEmulator": "1.1.1",
    "tpmHsm": "1.1.2",
    "diceEmulator": "1.1.1",
    "dice": "1.1.1",
    "x509": "1.1.4",
    "provisioningDevice": "1.8.4",
    "provisioningService": "1.7.0"
}

new
{
    "device": "1.27.0",
    "service": "1.26.0",
    "deps": "0.11.0",
    "securityProvider": "1.3.0",
    "tpmEmulator": "1.1.1",
    "tpmHsm": "1.1.2",
    "diceEmulator": "1.1.1",
    "dice": "1.1.1",
    "x509": "1.1.4",
    "provisioningDevice": "1.8.5",
    "provisioningService": "1.7.0"
}

### CODE REVIEW

**Review by abhipsaMisra — APPROVED** [review]

**Comment by barustum** [comment]
PR description mentions this:
com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.8.5

This should be 1.8.8, right?

**Comment by abhipsaMisra** [comment]
""provisioningDevice": "1.8.8"," - this confused me 😆
the actual file has it correct!

**Comment by barustum** [comment]
> PR description mentions this:
> com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.8.5
> 
> This should be 1.8.8, right?

actually seems like release notes should be 1.8.5

**Comment by timtay-microsoft** [comment]
I fixed the 1.8.8, good catch you two

**Comment by timtay-microsoft** [comment]
I must have mistyped, because the files being updated are all 1.8.5 as expected

**Review by barustum — APPROVED** [review]

**Pull request merged**
