### PR TITLE
Feature Request: Enable to set tags, desiredProperties and reportedProperties of a `Twin`

### PR DESCRIPTION
**Pull request by yilmaznaslan**
# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-java/blob/main/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- I submitted this PR against the correct branch: 
  - [x] This pull-request is submitted against the `main` branch. 

# Description of the problem
Editing/setting the `tags` of a Twin via the SDK is not possible. This feature is already active in [Azure IoTHub Web UI](https://github.com/yilmaznaslan/azure-iot-dev-guide/blob/bugfix/addSetterForTwin/docs/TwinIssue.png) 

# Code Sample
https://github.com/yilmaznaslan/azure-iot-dev-guide/blob/bugfix/addSetterForTwin/src/main/java/org/example/azure/MainApplication.java
```
package org.example.azure;

import com.microsoft.azure.sdk.iot.service.exceptions.IotHubException;
import com.microsoft.azure.sdk.iot.service.twin.Twin;
import com.microsoft.azure.sdk.iot.service.twin.TwinClient;
import com.microsoft.azure.sdk.iot.service.twin.TwinCollection;

import java.io.IOException;

public class MainApplication {

    public static String iotHubConnectionString = "REPLACE_ME";

    public static void main(String[] args) throws Exception {
        patchDeviceTwin("dishwasher_2");
    }
    public static void patchDeviceTwin(String deviceId) throws IOException, IotHubException {
        TwinClient twinClient = new TwinClient(iotHubConnectionString);
        Twin twin = twinClient.get(deviceId);
        TwinCollection twinCollection = new TwinCollection();
        twinCollection.put("customerId", "null");
        twinCollection.put("country", "germany");
        twinCollection.put("SoftwareId", "xe123");
        //twin.setTags(twinCollection);
        twinClient.patch(twin);
    }
}
```

# Description of the solution
 Add a setter to `com.microsoft.azure.sdk.iot.service.twin.Twin#tags`

### CODE REVIEW

**Comment by timtay-microsoft** [comment]
You should already be capable of doing this to edit the twin tags:

```
package org.example.azure;

import com.microsoft.azure.sdk.iot.service.exceptions.IotHubException;
import com.microsoft.azure.sdk.iot.service.twin.Twin;
import com.microsoft.azure.sdk.iot.service.twin.TwinClient;
import com.microsoft.azure.sdk.iot.service.twin.TwinCollection;

import java.io.IOException;

public class MainApplication {

    public static String iotHubConnectionString = "REPLACE_ME";

    public static void main(String[] args) throws Exception {
        patchDeviceTwin("dishwasher_2");
    }
    public static void patchDeviceTwin(String deviceId) throws IOException, IotHubException {
        TwinClient twinClient = new TwinClient(iotHubConnectionString);
        Twin twin = twinClient.get(deviceId);
        TwinCollection twinCollection = twin.getTags();
        twinCollection.put("customerId", "null");
        twinCollection.put("country", "germany");
        twinCollection.put("SoftwareId", "xe123");
        twinClient.patch(twin);
    }
}
```

Is that enough, or do you also need the ability to set the entire TwinCollection instance for some reason?

**Comment by yilmaznaslan** [comment]
Hi @timtay-microsoft ,

Maybe I couldn't explain myself well. Without a setter on `TwinCollection` of `Twin` class it is not possible to update the `tags`of a twin instance after twin instance is initialized. However in the Azure Portal this is not the case ==> it is possible to update the twins tag attributes after device is created. See [Azure IoTHub Web UI](https://github.com/yilmaznaslan/azure-iot-dev-guide/blob/bugfix/addSetterForTwin/docs/TwinIssue.png)

**Comment by timtay-microsoft** [comment]
I'm still a little confused here. From your sample code above:

```java
TwinClient twinClient = new TwinClient(iotHubConnectionString);
Twin twin = twinClient.get(deviceId);
TwinCollection twinCollection = twin.getTags(); // this returns the map of tags. It can be freely added to/updated
twinCollection.put("country", "usa");
twin.setTags(twinCollection); //This (proposed) call isn't necessary. You have updated the map of tags that is already associated with this twin.
twinClient.patch(twin);
```

This minimal sample demonstrates all you need to do in order to add/update tags on a twin and then update your twin with those changes:

```java
TwinClient twinClient = new TwinClient(iotHubConnectionString);
Twin twin = twinClient.get(deviceId);
TwinCollection twinCollection = twin.getTags();
twinCollection.put("country", "usa");
twinClient.patch(twin);
```

Is the above sample not working for you?

**Comment by timtay-microsoft** [comment]
@yilmaznaslan did the above code work for you?

**Comment by yilmaznaslan** [comment]
Sorry I wasn't available for a week @timtay-microsoft. The proposed solution above does not work. I don't see any functionality assigning the `Twincollection` to a `twin`again after updating the values of the `Twincollection`. Maybe the code below can explain the problem better than my words;

```

public static void main(String[] args) throws Exception {
        patchDeviceTwin("dishwasher_2");
        getTwinTags("dishwasher_2");
    }
    public static void patchDeviceTwin(String deviceId) throws IOException, IotHubException {
        TwinClient twinClient = new TwinClient(iotHubConnectionString);
        Twin twin = twinClient.get(deviceId);
        TwinCollection twinCollection = new TwinCollection();
        twinCollection.put("customerId", "null");
        twinCollection.put("country", "usa");
        twinCollection.put("SoftwareId", "xe123");
        //twin.setTags(twinCollection);
        twinClient.patch(twin);
    }
    public static void getTwinTags(String deviceId) throws IOException, IotHubException {
        TwinClient twinClient = new TwinClient(iotHubConnectionString);
        Twin twin = twinClient.get(deviceId);
        TwinCollection twinCollection = twin.getTags();
        String countryValue  = twinCollection.get("country").toString();
        System.out.println("Country value of the twin is:" + countryValue);
        if(!countryValue.equals("usa")){
            System.out.println("Updating country tag has failed");
        }
    }

```

**Comment by timtay-microsoft** [comment]
One small change to your above code is all it takes to enable what you want:

```java
public static void main(String[] args) throws Exception {
        patchDeviceTwin("dishwasher_2");
        getTwinTags("dishwasher_2");
    }
    public static void patchDeviceTwin(String deviceId) throws IOException, IotHubException {
        TwinClient twinClient = new TwinClient(iotHubConnectionString);
        Twin twin = twinClient.get(deviceId);
        //TwinCollection twinCollection = new TwinCollection(); //don't do this
        TwinCollection twinCollection = twin.getTags(); // do this. Any changes to this twinCollection instance will be reflected once you call "twinClient.patch" below
        twinCollection.put("customerId", "null");
        twinCollection.put("country", "usa");
        twinCollection.put("SoftwareId", "xe123");
        //twin.setTags(twinCollection); // no need for this because you updated the tag collection in place
        twinClient.patch(twin);
    }
    public static void getTwinTags(String deviceId) throws IOException, IotHubException {
        TwinClient twinClient = new TwinClient(iotHubConnectionString);
        Twin twin = twinClient.get(deviceId);
        TwinCollection twinCollection = twin.getTags();
        String countryValue  = twinCollection.get("country").toString();
        System.out.println("Country value of the twin is:" + countryValue);
        if(!countryValue.equals("usa")){
            System.out.println("Updating country tag has failed");
        }
    }
```

**Comment by yilmaznaslan** [comment]
I finally understood the difference and how it works. But I must say it is a bit tricky to catch the connection between the `twinCollection.put("country", "usa");`
 and `twinClient.patch(twin);` methods. Thanks @timtay-microsoft for the explanation.

**Comment by timtay-microsoft** [comment]
It sounds like you are unblocked, then. Any objections to me closing this PR?

**Comment by yilmaznaslan** [comment]
Yepp, you can close the PR

**Pull request closed without merging**
