### PR TITLE
Bring latest from master to preview

### PR DESCRIPTION
**Pull request by bikamani**
Bringing in changes since [60fcb64](https://github.com/Azure/azure-iot-sdk-java/commit/60fcb647f36e5b86a1ed46040cf2b3a720ea7615)

This does not include PnP model changes yet as those changes are out for review and not checked in yet.

### CODE REVIEW

**Comment by timtay-microsoft** [comment]
How was this merge done? When I do a git pull from master into preview, I only have 8 file content conflicts. In your commit to resolve conflicts, there are 100+ files

**Comment by bikamani** [comment]
> It looks like you did a rebase pull which is why there is no merge commit and why you had to resolve conflicts in 100+ files. Don't do a rebase pull. Just create a branch from preview, pull in master, and resolve the 8 conflicts. That will keep the git history a lot cleaner

It's not rebase pull. I did merge master in branch created from preview. There were 8 conflicts which I resolved.

**Comment by timtay-microsoft** [comment]
Then is this https://github.com/Azure/azure-iot-sdk-java/pull/792/commits/84b595b98d6d5d81e82f4579b0dc55da64e98e9c the merge commit? Why did you rename the commit title?

**Comment by bikamani** [comment]
> Then is this [84b595b](https://github.com/Azure/azure-iot-sdk-java/commit/84b595b98d6d5d81e82f4579b0dc55da64e98e9c) the merge commit? Why did you rename the commit title?

Yes you are right, it is the merge commit. I recall ccommiting with this message after resolving conflicts. May be that's the reason it shows up like this.

**Comment by bikamani** [comment]
> when

That's definitely a good reminder.

**Pull request merged**
