### PR TITLE
Update readme with Baltimore cert update info

### PR DESCRIPTION
**Pull request by sharmasejal**
# Checklist
- [ ] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-java/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [ ] This pull-request is submitted against the `master` branch. 

# Reference/Link to the issue solved with this PR (if any)

# Description of the problem

# Description of the solution

### CODE REVIEW

**Review by abhipsaMisra — APPROVED** [review]

**Review by timtay-microsoft — CHANGES_REQUESTED** [review]
This isn't quite how a user should look at our certs. Our device client and module client constructors have optional parameters for taking custom SSLContexts. The readme should have something more like "Unless a custom SSLContext is provided, device clients and module clients will use the public certs for IoT Hub during the SSL handshake"

**Comment by timtay-microsoft** [comment]
The Java SDK doesn't look at the certs registered on the machine running the SDK, as far as I know. We just have a hardcoded public cert for IoT Hub embedded in our SDK that gets loaded. There are other options for adding extra trusted certs as well, but nothing automatic for the customer like this commit suggests.

**Comment by abhipsaMisra** [comment]
You can dismiss my approval @sharmasejal , as expected Java requires a different set of instructions!

**Review by timtay-microsoft — APPROVED** [review]

**Pull request merged**
