### PR TITLE
refactor(sample): Update sample code and README to show how a downstream device connects to an IoT Edge device

### PR DESCRIPTION
**Pull request by mrohera**
# Checklist
- [x ] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-java/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [ x] This pull-request is submitted against the `master` branch. 

# Reference/Link to the issue solved with this PR (if any)

# Description of the problem

Make it easier for users to connect downstream devices to an Azure IoT Edge device,
# Description of the solution
 
Updating the sample to highlights how a developer should put together a connection string for the Edge and install the relevant CA certificate required to authenticate the Azure IoT Edge server certificate.

### CODE REVIEW

**Comment by mrohera** [comment]
Done.

**Comment by timtay-microsoft** [comment]
Again, sorry for the delay on checking this in. Our CI system is acting up right now.

**Comment by mrohera** [comment]
Thank you for the update.

**Comment by jasmineymlo** [comment]
merge completed 0e56f22f79fcd0924195e3c56616de1b112d918c

**Pull request closed without merging**
