### PR TITLE
fix(iot-dev): Fix device client not sending user agent string with proxy tunnel request

### PR DESCRIPTION
**Pull request by timtay-microsoft**
#870

### CODE REVIEW

**Comment by timtay-microsoft** [comment]
> Why not define a message template and use that? It'll work the same, but would be easier to maintain?

I'm not sure I follow what a message template is in this context. What is that exactly?

**Comment by abhipsaMisra** [comment]
```java
private static final String messageFormat = "CONNECT %s %s\r\nHost: %s\r\nUser-Agent: %s\r\n\r\n";
private static final String messageFormatWithProxy = messageFormat  + "Proxy-Authorization: Basic %s\r\n";

connectMessage = String.format(messageFormat, hostWithPort, HTTP_VERSION_1_1, hostWithPort, TransportUtils.USER_AGENT_STRING)
OR
connectMessage = String.format(messageFormatWithProxy, hostWithPort, HTTP_VERSION_1_1, hostWithPort, TransportUtils.USER_AGENT_STRING, base64EncodedCredentials);
```

**Pull request merged**
