### PR TITLE
Merge preview into master

### PR DESCRIPTION
**Pull request by timtay-microsoft**
Typically, I'd make a PR for merging master into preview first, but the Java preview branch will be deleted once the multiplexing code is merged to Master since there are no other preview features at the moment.

The branch here (timtay/previewFI) contains all of the current preview code after it has been rebased on the master branch. It mostly just contains multiplexing code

### CODE REVIEW

**Comment by bikamani** [comment]
> Typically, I'd make a PR for merging master into preview first, but the Java preview branch will be deleted once the multiplexing code is merged to Master since there are no other preview features at the moment.
> 
> The branch here (timtay/previewFI) contains all of the current preview code after it has been rebased on the master branch. It mostly just contains multiplexing code

wouldn't it be better to cherry pick all multiplexing related commits?

**Comment by timtay-microsoft** [comment]
> wouldn't it be better to cherry pick all multiplexing related commits?

The preview branch itself is just multiplexing commits, so there is no need to cherry pick. There is no device streaming or PnP code to worry about in the preview branch

**Comment by vinagesh** [comment]
Do we really need to delete the branch after?

**Review by vinagesh — APPROVED** [review]

**Review by bikamani — APPROVED** [review]

**Comment by timtay-microsoft** [comment]
> Do we really need to delete the branch after?

We could keep it, but it would just be a slightly messier version of the master branch. When we get a new preview feature to code, we can just create a new preview branch. Is there some reason that you'd prefer we keep it though?

**Pull request merged**
