### PR TITLE
Getter setter for twin fields

### PR DESCRIPTION
**Pull request by tmahmood-microsoft**
# Checklist
- [ ] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-java/blob/main/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- I submitted this PR against the correct branch: 
  - [ ] This pull-request is submitted against the `main` branch. 

# Reference/Link to the issue solved with this PR (if any)

# Description of the problem

# Description of the solution

### CODE REVIEW

**Comment by tmahmood-microsoft** [comment]
\azp run

**Comment by timtay-microsoft** [comment]
Can you add a step to an existing e2e test that checks that this value is not null when it calls ```twinClient.getTwin()``` ?

**Review by timtay-microsoft — APPROVED** [review]
Just one small comment

**Comment by tmahmood-microsoft** [comment]
Updated e2e test to check CloudToDeviceMessageCount is not null

**Pull request merged**
