### PR TITLE
Importing and exporting devices supports tags now

### PR DESCRIPTION
**Pull request by JMayrbaeurl**
# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-java/blob/master/.github/CONTRIBUTING.md).
- [x] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [x] This pull-request is submitted against the `master` branch. 

# Reference/Link to the issue solved with this PR (if any)
Partial fix for #298

# Description of the problem
Importing and exporting devices didn't support tags

# Description of the solution
Added the tags section to the import and export json serialization/deserialization

### CODE REVIEW

**Comment by timtay-microsoft** [comment]
Could you please squash your commits? I'd be happy to merge this in afterwards.

**Comment by JMayrbaeurl** [comment]
Sorry. Done now

**Comment by timtay-microsoft** [comment]
Looks good, I'll get this merged in.

**Comment by timtay-microsoft** [comment]
The test "toJsonForTaggedDevices" you added isn't passing. Looks like the order of the tags didn't match the expected json:

```
junit.framework.ComparisonFailure: 
Expected :{"authentication":{"symmetricKey":{"primaryKey":"","secondaryKey":""},"type":"sas"},"tags":{"test01":"firstvalue","test02":"secondvalue"}}
Actual   :{"authentication":{"symmetricKey":{"primaryKey":"","secondaryKey":""},"type":"sas"},"tags":{"test02":"secondvalue","test01":"firstvalue"}}
```

**Comment by JMayrbaeurl** [comment]
Interesting by the way. Unit testing from Eclipse doesn't show this failure. Anyway. Since there's no guaranteed order for tags, I've changed the unit test accordingly

**Pull request merged**
