### PR TITLE
Fix: Bug fix for SasUri generation failure after disconnecting/connec…

### PR DESCRIPTION
**Pull request by tmahmood-microsoft**
The bug was reproducible when once a file is uploaded to blob storage and after client reconnection, the same process fails with null exception.
The issue was missing open() call to HttpsTransportManager object when the device client is opened after disconnection. 

Original GitHub issue: https://github.com/Azure/azure-iot-sdk-java/issues/1662

### CODE REVIEW

**Review by patilsnr — APPROVED** [review]

**Review by andyk-ms — APPROVED** [review]

**Comment by timtay-microsoft** [comment]
I'd rather see us remove the open/close methods on the ```HttpsTransportManager``` since http clients don't have that concept. Similarly, the ```FileUpload``` class has nothing to open/close, so we can remove that as well.

With the above, we'd instantiate the FileUpload class once (when the first file upload request is made) and never have to open/close/re-instantiate it again. Thoughts?

**Comment by tmahmood-microsoft** [comment]
> I'd rather see us remove the open/close methods on the `HttpsTransportManager` since http clients don't have that concept. Similarly, the `FileUpload` class has nothing to open/close, so we can remove that as well.
> 
> With the above, we'd instantiate the FileUpload class once (when the first file upload request is made) and never have to open/close/re-instantiate it again. Thoughts?

This makes more sense, yes. Since the `HttpsTransportManager` object does not get affected by client reconnection, we dont need to close/open it again.

**Review by timtay-microsoft — APPROVED** [review]

**Pull request merged**
