### PR TITLE
Bump package versions for release on 2020-03-13

### PR DESCRIPTION
**Pull request by bikamani**
## Java IotHub Service Client (com.microsoft.azure.sdk.iot:iot-service-client:1.21.0)

- Enables new security functionality to specify how hub should authenticate when working with a storage account when running import/export devices jobs. Initially, this feature has limited availability, starting with 3 public cloud Azure regions. Since it is not yet widely available, this functionality must be explicitly enabled by the user. See below (1) for details.
  - New property `JobProperties.StorageAuthenticationType` for use in import/export devices jobs.
  - Added overloaded methods: `RegistryManager.importDevicesAsync`, `RegistryManager.importDevices`, `RegistryManager.exportDevicesAsync` and `RegistryManager.exportDevices`. The overloads take a `JobProperties` instance so the user can pass all required and any optional parameters.
  - Two factory methods to make it easier to call `importDevicesAsync`,  `importDevices`, `exportDevicesAsync` and  `exportDevices` making it clear which properties are required and which are optional. They are `JobProperties.createForImportJob` and `JobProperties.createForExportJob` respectively.
- Updated reference to com.microsoft.azure.sdk.iot:iot-deps

> (1) To enable this functionality, this version of the SDK will require setting an environment variable of `EnableStorageIdentity` to `1`. Once this feature is widely available, another SDK version will be released with this requirement removed.

## Java IotHub Device Client (com.microsoft.azure.sdk.iot:iot-device-client:1.20.2)

- Upgraded version of Azure Storage dependency
- Updated reference to com.microsoft.azure.sdk.iot:iot-deps

## Java SDK Dependency (com.microsoft.azure.sdk.iot:iot-deps:0.9.2)

- New enum `StorageAuthenticationType` to specify key-based or identity-based authentication.
- Adding support for JobPropertiesParser for a new enum `StorageAuthenticationType`

## Java Provisioning Security x509 Provider (com.microsoft.azure.sdk.iot.provisioning.security:x509-provider:1.1.4)

- Upgraded version of bouncy castle dependency

## Java Provisioning Device Client (com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.8.1)

- Updated reference to com.microsoft.azure.sdk.iot.provisioning.security:x509-provider
- Updated reference to com.microsoft.azure.sdk.iot:iot-deps

## Java Provisioning Device Client (com.microsoft.azure.sdk.iot.provisioning:provisioning-service-client:1.6.1)

- Updated reference to com.microsoft.azure.sdk.iot.provisioning.security:x509-provider
- Updated reference to com.microsoft.azure.sdk.iot:iot-deps

Merge Pull Request
#717, #725, #726, #723 

Maven packages
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.20.2/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-service-client/1.21.0/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-deps/0.9.2/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot.provisioning.security/x509-provider/1.1.4/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot.provisioning/provisioning-device-client/1.8.1/jar
https://search.maven.org/artifact/com.microsoft.azure.sdk.iot.provisioning/provisioning-service-client/1.6.1/jar

old
{
    "device": "1.20.1",
    "service": "1.20.1",
    "deps": "0.9.1",
    "securityProvider": "1.3.0",
    "tpmEmulator": "1.1.1",
    "tpmHsm": "1.1.2",
    "diceEmulator": "1.1.1",
    "dice": "1.1.1",
    "x509": "1.1.3",
    "provisioningDevice": "1.8.0",
    "provisioningService": "1.6.0"
}

new
{
    "device": "1.20.2",
    "service": "1.21.0",
    "deps": "0.9.2",
    "securityProvider": "1.3.0",
    "tpmEmulator": "1.1.1",
    "tpmHsm": "1.1.2",
    "diceEmulator": "1.1.1",
    "dice": "1.1.1",
    "x509": "1.1.4",
    "provisioningDevice": "1.8.1",
    "provisioningService": "1.6.1"
}

### CODE REVIEW

**Comment by timtay-microsoft** [comment]
Instead of 

"Updated reference to com.microsoft.azure.sdk.iot:iot-deps"

can you say

"Updated iot-deps version to latest"

It'll be easier for users to understand

**Comment by bikamani** [comment]
> "Updated iot-deps version to latest"

@timtay-microsoft will do that.

**Comment by timtay-microsoft** [comment]
And can you simplify your notes on the JobProperties changes? Explaining why we added new auth types for JobProperties is good, and explaining the limited availability is good, but beyond that, the 3 innermost bullet points are very busy. As a user, I would expect something similar to:

- Added new APIs to support new role-based authentication type for Jobs that is compatible with limited IotHub regions

The release notes are not the place to document how to use the new feature

**Comment by timtay-microsoft** [comment]
Otherwise, the code changes look good to me

**Comment by bikamani** [comment]
> And can you simplify your notes on the JobProperties changes? Explaining why we added new auth types for JobProperties is good, and explaining the limited availability is good, but beyond that, the 3 innermost bullet points are very busy. As a user, I would expect something similar to:
> 
> * Added new APIs to support new role-based authentication type for Jobs that is compatible with limited IotHub regions
> 
> The release notes are not the place to document how to use the new feature

@timtay-microsoft We are adding environmental variable to support limited availability of this new authentication. Also we are using release notes to aware users on how to use it as this is something user needs to do if they want to use this feature. C# is doing the same way. If you still think it is inappropriate to add it here, let's take it offline.

@drwill-ms  do you have any comments for this?

**Comment by timtay-microsoft** [comment]
Is this new JobProperties feature documented within the code itself? If it is, then I don't see why we are documenting it here, too

**Comment by bikamani** [comment]
> Is this new JobProperties feature documented within the code itself? If it is, then I don't see why we are documenting it here, too

@timtay-microsoft It is documented (not in great detail though) in IotHubConnectionString class. Do you expect customers to look for this in IotHubConnectionString class? I don't expect that.

**Comment by timtay-microsoft** [comment]
> > Is this new JobProperties feature documented within the code itself? If it is, then I don't see why we are documenting it here, too
> 
> @timtay-microsoft It is documented (not in great detail though) in IotHubConnectionString class. Do you expect customers to look for this in IotHubConnectionString class? I don't expect that.

Why wasn't it documented in the JobClient class? The user who wants to use this new auth type uses the JobClient, so that's where I'd expect this to be documented

**Comment by bikamani** [comment]
> > > Is this new JobProperties feature documented within the code itself? If it is, then I don't see why we are documenting it here, too
> > 
> > 
> > @timtay-microsoft It is documented (not in great detail though) in IotHubConnectionString class. Do you expect customers to look for this in IotHubConnectionString class? I don't expect that.
> 
> Why wasn't it documented in the JobClient class? The user who wants to use this new auth type uses the JobClient, so that's where I'd expect this to be documented

I think you meant JobProperties class? I realize now that I should have  added this in API headers in RegistryManager. But having said that, if we don't include as part of release notes at this point - IotHubConnectionString is definitely not the place where anyone would look for this. I had added it as this environment variable flag is added in here for simplicity.

**Comment by timtay-microsoft** [comment]
Okay, documenting the new API in the release notes is fine for now. Please put up a PR soon that documents this in the public API where users expect it to be, though

**Comment by bikamani** [comment]
> > > Is this new JobProperties feature documented within the code itself? If it is, then I don't see why we are documenting it here, too
> > 
> > 
> > @timtay-microsoft It is documented (not in great detail though) in IotHubConnectionString class. Do you expect customers to look for this in IotHubConnectionString class? I don't expect that.
> 
> Why wasn't it documented in the RegistryManager class or JobProperties class? The user who wants to use this new auth type uses the RegistryManager, so that's where I'd expect this to be documented



> Okay, documenting the new API in the release notes is fine for now. Please put up a PR soon that documents this in the public API where users expect it to be, though

Definitely, adding a PR just now.

**Comment by timtay-microsoft** [comment]
Nice try Bert. These pipelines are top secret

**Pull request merged**
