### PR TITLE
RegistryManager.removeDevice: Contents of If-Match header in http request must be double quoted

### PR DESCRIPTION
**Pull request by JMayrbaeurl**
# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-java/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [x] This pull-request is submitted against the `master` branch. 

# Reference/Link to the issue solved with this PR (if any)
Solves #292 

# Description of the problem
Constantly fails with IotHubPreconditionFailedException 

# Description of the solution
The contents of the If-Match http request header, that contains the etag of the device, gets surrounded with double quotes

### CODE REVIEW

**Comment by timtay-microsoft** [comment]
This change breaks a few unit tests for RegistryManagerTest.java. Also, the removeModule flow should also change to include quotes around the etag.

I think there is a better way to fix this issue, so I created a [branch](https://github.com/Azure/azure-iot-sdk-java/tree/eTagFix) with a different fix. Can you test if this works for you now? Including the remove module flow?

**Comment by JMayrbaeurl** [comment]
You are right. Fixing it for devices and modules is even better. I've tested your proposed changes and they work with my tests correctly. Therefore I've changed this PR to include your fix from the specified branch. PR should now be ready to be merged.

**Comment by timtay-microsoft** [comment]
Glad to hear it! I'll get this merged in right away. Thanks for the PR!

**Comment by timtay-microsoft** [comment]
There were a few other unit tests that I had to fix before this fix could be merged in, so I had to merge directly from my "eTagFix" branch instead of this PR. The fix has been checked in, though, so I'm going to close this PR.

**Comment by JMayrbaeurl** [comment]
@timtay-microsoft Did you really merge all changes to master? BaseDeviceTest.conversionToDeviceParser() fails, because the expected value for the eTag isn't surrounded by double quotes! The same problem for 

```
Failed tests:
  BaseDeviceTest.conversionToDeviceParser:188 expected:<["1234"]> but was:<[1234]>
  DeviceTest.conversionToDeviceParser:273 expected:<["1234"]> but was:<[1234]>
  ModuleTest.conversionToDeviceParser:322 expected:<["1234"]> but was:<[1234]>
```

**Comment by timtay-microsoft** [comment]
Yes, all the changes were successfully merged into master, and those tests are passing. What branch are you seeing those tests failing in? Your PR branch, or master?

**Pull request closed without merging**
