### PR TITLE
Update java-api-reference

### PR DESCRIPTION
**Pull request by jlorich**
Updated java-api-reference to be the correct javadoc url since it currently 404s.  However, I do wonder if we should be referencing https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.device?view=azure-java-stable instead of the JavaDoc.  We seem to have both and use them inconsistently page to page.

### CODE REVIEW

**Comment by timtay-microsoft** [comment]
@sindhu-nagesh for awareness since she last looked at our github pages, but this looks good to me

**Comment by vinagesh** [comment]
Looks good to me too!

**Review by vinagesh — APPROVED** [review]

**Review by timtay-microsoft — APPROVED** [review]

**Pull request merged**
