### PR TITLE
Arslava/callback

### PR DESCRIPTION
**Pull request by arslava**
# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-java/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [ ] This pull-request is submitted against the `master` branch. 

# Reference/Link to the issue solved with this PR (if any)

# Description of the problem
https://docs.microsoft.com/en-us/answers/questions/148946/java-sdk-devicetwin-desired-properties-update-call.html
If multiple desired properties are updated at the same time, callbacks are executed for each property.  This is not efficient, a single callback, which references all updated properties should be executed.

# Description of the solution
Defined a new callback which will be executed in the case if multiple desired properties of device twin are modified.

### CODE REVIEW

**Comment by timtay-microsoft** [comment]
Hi Slava, would you mind if I contributed some code to this branch on your fork? I'd like to add some tests to go along with this feature

**Comment by arslava** [comment]
> Hi Slava, would you mind if I contributed some code to this branch on your fork? I'd like to add some tests to go along with this feature

No problem at all, I appreciate and comments and suggestions

**Comment by timtay-microsoft** [comment]
@arslava I don't have write access to your fork, I just forked your fork and created a PR with my suggested edits. You can see it [here](https://github.com/arslava/azure-iot-sdk-java/pull/1). Give it a try to make sure everything still works the way you expect it to

**Comment by timtay-microsoft** [comment]
@arslava can you give me write access to your fork? I have to make some small changes to the test code in this PR. I shouldn't have to change anything in the implementation code.

**Review by timtay-microsoft — APPROVED** [review]

**Pull request merged**
