### PR TITLE
Connection State propagation to DeviceTwinDevice https://github.com/Azure/azure-iot-sdk-java/issues/520

### PR DESCRIPTION
**Pull request by pawankaushal**
Connection State is now properly propagated to DeviceTwinDevice object
along with Configurations
This was missing in the fix provide earlier for https://github.com/Azure/azure-iot-sdk-java/issues/520

### CODE REVIEW

**Comment by pawankaushal** [comment]
I have also added propagation of configurations properties to the devicetwindevice

**Comment by timtay-microsoft** [comment]
Thanks for finding this bug. I went ahead and wrote some unit and e2e tests to make sure that this feature isn't broken in the future. I put it into PR #536

**Comment by pawankaushal** [comment]
do you see the possibility of merging my changes and adding your unit tests on top of it?

**Comment by timtay-microsoft** [comment]
Since this fix was added as a part of a different PR, I'm going to close this PR. Thanks again for providing the fix!

**Pull request closed without merging**
