### PR TITLE
Fixes [Verbose or redundant code constructs] 'StringBuilder' can be replaced with 'String' (31)

### PR DESCRIPTION
**Pull request by jamdavi**
Fixes the [Verbose or redundant code constructs] 'StringBuilder' can be replaced with 'String' warning.

### CODE REVIEW

**Review by barustum — APPROVED** [review]

**Comment by barustum** [comment]
Curious to know why the recommendation to replace stringbuilder with string. Probably an optimization?

**Comment by jamdavi** [comment]
> Curious to know why the recommendation to replace stringbuilder with string. Probably an optimization?

Yes, per the docs it checks for SB being used for a constant number of concats.

**Pull request merged**
